/*
 * Filename: sc_brakelight_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass
 * name: sc_brakeLight
 * shortname: brakeLight
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_brakelight_type.h"

#include "led.h"



/* USER CODE START SC_BRAKELIGHT_INCLUDE */

/* USER CODE END SC_BRAKELIGHT_INCLUDE */




/* USER CODE START SC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SC_BRAKELIGHT_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_BRAKELIGHT signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_BRAKELIGHT_driverOut(const SC_BRAKELIGHT_data_t  *const data)
{
	/* USER CODE START driverOutSC_BRAKELIGHT */
    if(data->brakeLight == 0)
    {
        LED_Set(LED_RED, LED_ON);
    }
    else
    {
        LED_Set(LED_RED, LED_OFF);
    }
    
	return RC_SUCCESS;
	/* USER CODE END driverOutSC_BRAKELIGHT */
}



