/*
 * Filename: sc_engine_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass
 * name: sc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_engine_type.h"

#include "led.h"



/* USER CODE START SC_ENGINE_INCLUDE */

/* USER CODE END SC_ENGINE_INCLUDE */




/* USER CODE START SC_ENGINE_USERDEFINITIONS */

/* USER CODE END SC_ENGINE_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_ENGINE signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_ENGINE_driverOut(const SC_ENGINE_data_t  *const data)
{
	/* USER CODE START driverOutSC_ENGINE */
    if(data->engineSpeed > 0)
    {
        uint8_t greenChannel = data->engineSpeed;
        LED_RGB_Set(0,greenChannel,0);
    }
    else
    {
        LED_RGB_Set(0, 0, 0);
    }

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_ENGINE */
}
