/*
 * Filename: swc_remote.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_remote
 * shortname: remote
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_remote.h"
#include "WatchDogTimer.h"



/* USER CODE START SWC_REMOTE_INCLUDE */

/* USER CODE END SWC_REMOTE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_REMOTE_USERDEFINITIONS */

/* USER CODE END SWC_REMOTE_USERDEFINITIONS */



/*
 * component: swc_remote
 * cycletime: 10
 * description: Runnable
 * events: 
 * name: REMOTE_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_io
 */
void REMOTE_readJoystick_run(RTE_event ev)
{
	
	/* USER CODE START REMOTE_readJoystick_run */
    RC_t ret = RTE_SC_JOYSTICK_pullPort(&SO_JOYSTICK_signal);
    
    if(ret != RC_SUCCESS)
    {
        UART_LOG_PutString("\r\nFailure: Joystick driver value not updated on SO_JOYSTICK_signal");
    }

    WD_Alive(run_remote_pos);
    /* USER CODE END REMOTE_readJoystick_run */
}

/* USER CODE START SWC_REMOTE_FUNCTIONS */

/* USER CODE END SWC_REMOTE_FUNCTIONS */

