/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"
#include "WatchDogTimer.h"


/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Runnable
 * events: ev_joystick_onData
 * name: CONTROL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void CONTROL_calcControl_run(RTE_event ev)
{
	/* USER CODE START CONTROL_calcControl_run */
    SC_SPEED_data_t speedValue = SC_SPEED_INIT_DATA;
    RC_t ret = RC_SUCCESS;
    
    if(RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal).joystick_y > 0)
    {
        speedValue.speed = 2 * RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal).joystick_y;
    }
    else
    {
        speedValue.speed = 0;
    }
    
    ret = RTE_SC_SPEED_set(&SO_SPEED_signal, speedValue);
    
    if(ret != RC_SUCCESS)
    {
        UART_LOG_PutString("\r\nSpeed Object update unsuccessful");
    }
    WD_Alive(run_calcControl_pos);
    /* USER CODE END CONTROL_calcControl_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

