/*
 * Filename: swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_brakeLight
 * shortname: brakeLight
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"
#include "WatchDogTimer.h"



/* USER CODE START SWC_BRAKELIGHT_INCLUDE */

/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
 * component: swc_brakeLight
 * cycletime: 0
 * description: Runnable
 * events: ev_speed_onData
 * name: BRAKELIGHT_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: so_brakeLight
 * task: tsk_control
 */
void BRAKELIGHT_setBrakeLight_run(RTE_event ev)
{
	/* USER CODE START BRAKELIGHT_setBrakeLight_run */
    SC_BRAKELIGHT_data_t brakeLightValue = SC_BRAKELIGHT_INIT_DATA;
    RC_t ret = RC_SUCCESS;
    
    if (RTE_SC_SPEED_get(&SO_SPEED_signal).speed == 0)
    {
        brakeLightValue.brakeLight = RTE_SC_SPEED_get(&SO_SPEED_signal).speed; 
    }
    else
    {
        brakeLightValue.brakeLight = 1;
    }
    
    ret = RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal, brakeLightValue);
    
    if(ret == RC_SUCCESS)
    {
        ret = RTE_SC_BRAKELIGHT_pushPort(&SO_BRAKELIGHT_signal);
    }
    else
    {
        UART_LOG_PutString("\r\nError: Brakelight signal not able to write to Driver");
    }
    
    WD_Alive(run_brakelight_pos);
    /* USER CODE END BRAKELIGHT_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

