/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"
#include "WatchDogTimer.h"



/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void ENGINE_setEngine_run(RTE_event ev)
{
	/* USER CODE START ENGINE_setEngine_run */
    SC_ENGINE_data_t engineSpeedValue = SC_ENGINE_INIT_DATA;
    RC_t ret = RC_SUCCESS;
    
    if(RTE_SC_SPEED_getAge(&SO_SPEED_signal) < 10) 
    {
        engineSpeedValue.engineSpeed = RTE_SC_SPEED_get(&SO_SPEED_signal).speed;
    }
    else
    {
        engineSpeedValue.engineSpeed = 0;
    }
    
    ret = RTE_SC_ENGINE_set(&SO_ENGINE_signal, engineSpeedValue);
    
    if(ret == RC_SUCCESS)
    {
        ret = RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal);
    }
    else
    {
        UART_LOG_PutString("\r\nERROR: Engine signal object not updated with engine signal value");
    }
    
    WD_Alive(run_engine_pos);
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

